version: "3.7"
services:
  ## Cluster ZooKeeper
  # ZooKeeper_1
  zoo_1:
    image: zookeeper:3.7
    restart: always
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo_1:2888:3888;2181 server.2=zoo_2:2888:3888;2181 server.3=zoo_3:2888:3888;2181

  # ZooKeeper_2
  zoo_2:
    image: zookeeper:3.7
    restart: always
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo_1:2888:3888;2181 server.2=zoo_2:2888:3888;2181 server.3=zoo_3:2888:3888;2181

  # ZooKeeper_3
  zoo_3:
    image: zookeeper:3.7
    restart: always
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo_1:2888:3888;2181 server.2=zoo_2:2888:3888;2181 server.3=zoo_3:2888:3888;2181

  ## Cluster ClickHouse ...
  # Master
  ch_master:
    image: yandex/clickhouse-server:21.6.3.14
    restart: always
    depends_on:
      - ch_slave_1
      - ch_slave_2
      - ch_slave_3
      - ch_slave_4
    ports:
      - 9000:9000
      - 8123:8123
    volumes:
      - "ch-master-data:/var/lib/clickhouse"
      - "ch-master-logs:/var/log/clickhouse-server"
      - "./clickhouse-config:/etc/clickhouse-server/"

  # Slave 1
  ch_slave_1:
    image: yandex/clickhouse-server:21.6.3.14
    restart: always
    depends_on:
      - zoo_1
      - zoo_2
      - zoo_3
    ports:
      - 9001:9000
      - 8124:8123
    volumes:
      - "ch-slave-1-data:/var/lib/clickhouse"
      - "ch-slave-1-logs:/var/log/clickhouse-server"
      - "./clickhouse-config:/etc/clickhouse-server/"

  # Slave 2
  ch_slave_2:
    image: yandex/clickhouse-server:21.6.3.14
    restart: always
    depends_on:
      - zoo_1
      - zoo_2
      - zoo_3
    ports:
      - 9002:9000
      - 8125:8123
    volumes:
      - "ch-slave-2-data:/var/lib/clickhouse"
      - "ch-slave-2-logs:/var/log/clickhouse-server"
      - "./clickhouse-config:/etc/clickhouse-server/"

  # Slave 3
  ch_slave_3:
    image: yandex/clickhouse-server:21.6.3.14
    restart: always
    depends_on:
      - zoo_1
      - zoo_2
      - zoo_3
    ports:
      - 9003:9000
      - 8126:8123
    volumes:
      - "ch-slave-3-data:/var/lib/clickhouse"
      - "ch-slave-3-logs:/var/log/clickhouse-server"
      - "./clickhouse-config:/etc/clickhouse-server/"

# Slave 4
  ch_slave_4:
    image: yandex/clickhouse-server:21.6.3.14
    restart: always
    depends_on:
      - zoo_1
      - zoo_2
      - zoo_3
    ports:
      - 9004:9000
      - 8127:8123
    volumes:
      - "ch-slave-4-data:/var/lib/clickhouse"
      - "ch-slave-4-logs:/var/log/clickhouse-server"
      - "./clickhouse-config:/etc/clickhouse-server/"

volumes:
  # Volume for Master
  ch-master-data: {}
  ch-master-logs: {}
  # Volume for Slave 1
  ch-slave-1-data: {}
  ch-slave-1-logs: {}
  # Volume for Slave 2
  ch-slave-2-data: {}
  ch-slave-2-logs: {}
  # Volume for Slave 3
  ch-slave-3-data: {}
  ch-slave-3-logs: {}
  # Volume for Slave 4
  ch-slave-4-data: {}
  ch-slave-4-logs: {}